Update preprod-eu.yaml

diff --git a/.github/workflows/preprod-eu.yaml b/.github/workflows/preprod-eu.yaml
--- a/.github/workflows/preprod-eu.yaml
+++ b/.github/workflows/preprod-eu.yaml
@@ -1,34 +1,38 @@
-name: Preprod EU Deployment
+name: Preprod - EU Region
 
 on:
   pull_request:
     types: [opened, edited, reopened]
+    paths:
+      - .github/workflows/preprod-eu.yaml
 
 jobs:
-  deploy:
+  deploy-preprod-eu:
+    if: >
+      github.event.pull_request.title contains 'ap' &&
+      github.event.pull_request.title contains 'eu' &&
+      github.event.pull_request.title contains 'us' &&
+      github.event.pull_request.title contains 'rG'
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Parse PR Body
-        id: parse_pr
+      - name: Validate Preprod EU Deployment
         run: |
           PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
           PREPROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Preprod: `)[^`]+')
+
+          if [ "$PREPROD_SELECTED" != "Y" ]; then
+            echo "Preprod environment not selected for deployment. Skipping."
+            exit 0
+          fi
+
           PREPROD_IMAGE_EU=$(echo "$PR_BODY" | grep -A 3 "Preprod Environment" | grep "EU Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
+          if [ -z "$PREPROD_IMAGE_EU" ]; then
+            echo "Error: Missing image tag for Preprod EU Region."
+            exit 1
+          fi
 
-          echo "PREPROD_SELECTED=$PREPROD_SELECTED" >> $GITHUB_ENV
-          echo "PREPROD_IMAGE_EU=$PREPROD_IMAGE_EU" >> $GITHUB_ENV
-
-      - name: Validate and Print Values
-        run: |
-          if [ "$PREPROD_SELECTED" == "Y" ]; then
-            if [ -z "$PREPROD_IMAGE_EU" ]; then
-              echo "Error: Missing image tag value for Preprod EU Region."
-              exit 1
-            fi
-            echo "Preprod EU Region selected with image tag: $PREPROD_IMAGE_EU"
-          else
-            echo "Preprod EU Region not selected. Skipping deployment."
+          echo "Deploying Preprod - EU Region with image tag: $PREPROD_IMAGE_EU"
