Update prod-ap.yaml

diff --git a/.github/workflows/prod-ap.yaml b/.github/workflows/prod-ap.yaml
--- a/.github/workflows/prod-ap.yaml
+++ b/.github/workflows/prod-ap.yaml
@@ -1,34 +1,38 @@
-name: Prod AP Deployment
+name: Prod - AP Region
 
 on:
   pull_request:
     types: [opened, edited, reopened]
+    paths:
+      - .github/workflows/prod-ap.yaml
 
 jobs:
-  deploy:
+  deploy-prod-ap:
+    if: >
+      github.event.pull_request.title contains 'ap' &&
+      github.event.pull_request.title contains 'eu' &&
+      github.event.pull_request.title contains 'us' &&
+      github.event.pull_request.title contains 'rG'
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Parse PR Body
-        id: parse_pr
+      - name: Validate Prod AP Deployment
         run: |
           PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
           PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)[^`]+')
+
+          if [ "$PROD_SELECTED" != "Y" ]; then
+            echo "Prod environment not selected for deployment. Skipping."
+            exit 0
+          fi
+
           PROD_IMAGE_AP=$(echo "$PR_BODY" | grep -A 3 "Prod Environment" | grep "AP Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
+          if [ -z "$PROD_IMAGE_AP" ]; then
+            echo "Error: Missing image tag for Prod AP Region."
+            exit 1
+          fi
 
-          echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV
-          echo "PROD_IMAGE_AP=$PROD_IMAGE_AP" >> $GITHUB_ENV
-
-      - name: Validate and Print Values
-        run: |
-          if [ "$PROD_SELECTED" == "Y" ]; then
-            if [ -z "$PROD_IMAGE_AP" ]; then
-              echo "Error: Missing image tag value for Prod AP Region."
-              exit 1
-            fi
-            echo "Prod AP Region selected with image tag: $PROD_IMAGE_AP"
-          else
-            echo "Prod AP Region not selected. Skipping deployment."
+          echo "Deploying Prod - AP Region with image tag: $PROD_IMAGE_AP"
