Update prod-us.yaml

diff --git a/.github/workflows/prod-us.yaml b/.github/workflows/prod-us.yaml
--- a/.github/workflows/prod-us.yaml
+++ b/.github/workflows/prod-us.yaml
@@ -1,34 +1,38 @@
-name: Prod EU Deployment
+name: Prod - US Region
 
 on:
   pull_request:
     types: [opened, edited, reopened]
+    paths:
+      - .github/workflows/prod-us.yaml
 
 jobs:
-  deploy:
+  deploy-prod-us:
+    if: >
+      github.event.pull_request.title contains 'ap' &&
+      github.event.pull_request.title contains 'eu' &&
+      github.event.pull_request.title contains 'us' &&
+      github.event.pull_request.title contains 'rG'
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Parse PR Body
-        id: parse_pr
+      - name: Validate Prod US Deployment
         run: |
           PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
           PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)[^`]+')
-          PROD_IMAGE_EU=$(echo "$PR_BODY" | grep -A 3 "Prod Environment" | grep "US Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
 
-          echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV
-          echo "PROD_IMAGE_US=$PROD_IMAGE_EU" >> $GITHUB_ENV
+          if [ "$PROD_SELECTED" != "Y" ]; then
+            echo "Prod environment not selected for deployment. Skipping."
+            exit 0
+          fi
 
-      - name: Validate and Print Values
-        run: |
-          if [ "$PROD_SELECTED" == "Y" ]; then
-            if [ -z "$PROD_IMAGE_US" ]; then
-              echo "Error: Missing image tag value for Prod US Region."
-              exit 1
-            fi
-            echo "Prod US Region selected with image tag: $PROD_IMAGE_US"
-          else
-            echo "Prod US Region not selected. Skipping deployment."
+          PROD_IMAGE_US=$(echo "$PR_BODY" | grep -A 3 "Prod Environment" | grep "US Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
+          if [ -z "$PROD_IMAGE_US" ]; then
+            echo "Error: Missing image tag for Prod US Region."
+            exit 1
+          fi
+
+          echo "Deploying Prod - US Region with image tag: $PROD_IMAGE_US"
